### PR TITLE
#[cfg(miri) in the fmt exhaustiveness test was merged

### PR DESCRIPTION
**Pull request by saethlin**
https://github.com/rust-lang/rust/pull/117946 was merged, so this patch has been upstreamed.

### CODE REVIEW

**Comment by saethlin** [comment]
Ah. CI won't pass until we have a nightly with the patch.

**Comment by RalfJung** [comment]
We have a nightly with the patch, otherwise the CI would not have failed.

**Comment by RalfJung** [comment]
Superseded by 0129451.

**Comment by saethlin** [comment]
Smh did the new nightly come out after I signed off? I need to keep track of what time they're available.

**Comment by RalfJung** [comment]
CI of this repo runs against the latest nightly. So when CI failed, the nightly was definitely out already.

Nightlies usually become available around 1am UTC, I think. (The release process starts shortly after midnight UTC, but it takes a while.)

**Pull request closed without merging**
